# Dependencies
markdown:         redcarpet
gems:             [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Kevin Jiao
tagline:          'A Jekyll theme'
description:      'Software Engineer, Student@UC Berkeley'
url:              kevinjiao.github.io
baseurl:          /

author:
  name:           'Kevin Jiao'

paginate:         2

# Custom vars
version:          2.1.0

github:           "http://github.com/kevinjiao"
linkedin:         "http://linkedin.com/in/kjiao"
bitbucket:        "http://bitbucket.org/kevinjiao"
email:            "mailto:kevin.jiao@berkeley.edu?Subject=Have%20My%20Babies"
